export const arrCountries: Array<string> = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bangladesh",
    "Barbados",
    "Bahrain",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bulgaria",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Burkina Faso",
    "Burundi",
    "Bhutan",
    "Vanuatu",
    "Hungary",
    "Venezuela",
    "Vietnam",
    "Gabon",
    "Haiti",
    "Ghana",
    "Greece",
    "Grenada",
    "Georgia",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Egypt",
    "Zambia",
    "Samoa", 
    "Zimbabwe",
    "Israel",
    "India",
    "Indonesia",
    "Jordan",
    "Ireland",
    "Iceland",
    "Spain",
    "Italy",
    "Kazakhstan",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Qatar",
    "Kenya",
    "Kyrgyzstan",
    "Kiribati",
    "China",
    "Colombia",
    "Comoros",
    "Congo (Democratic Republic)",
    "Congo (Republic)",
    "Costa Rica",
    "Croatia", 
    "Cuba",
    "Kuwait",
    "Laos",
    "Latvia",
    "Lebanon",
    "Libya",
    "Lithuania",
    "Liechtenstein",
    "Luxembourg",
    "Mauritania",
    "Mauritius",
    "Madagascar",
    "North Macedonia", 
    "Malawi",
    "Malaysia",
    "Mali",
    "Maldives",
    "Malta",
    "Morocco",
    "Martinique",
    "Mexico",
    "Mozambique",
    "Moldova",
    "Mongolia",
    "Namibia",
    "Nauru",
    "Nepal",
    "Niger",
    "Nigeria",
    "Netherlands",
    "Nicaragua",
    "Norway",
    "New Zealand",
    "UAE",
    "Oman",
    "Pakistan",
    "Palau",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Poland",
    "Portugal",
    "South Korea",
    "Republic of the Congo",
    "Russia",
    "Rwanda",
    "Romania",
    "El Salvador",
    "San Marino",
    "Eswatini", 
    "Seychelles",
    "Senegal",
    "Serbia",
    "Singapore",
    "Syria",
    "Slovakia",
    "Slovenia",
    "United States of America",
    "Solomon Islands",
    "Somalia",
    "Sudan",
    "Suriname",
    "Sierra Leone",
    "Tajikistan",
    "Thailand",
    "Tanzania",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkmenistan",
    "Turkey",
    "Uganda",
    "Uzbekistan",
    "Ukraine",
    "Uruguay",
    "Fiji",
    "Philippines",
    "Finland",
    "France",
    "Central African Republic",
    "Chad",
    "Czech Republic",
    "Chile",
    "Switzerland",
    "Sweden",
    "Sri Lanka",
    "Ecuador",
    "Equatorial Guinea",
    "Estonia",
    "Ethiopia",
    "Yugoslavia (partially recognized)",
    "South Africa",
    "South Sudan",
    "Jamaica",
    "Japan"]